### ISSUE TITLE
Dataset filtering (CLIP similarity)

### ISSUE THREAD

**Issue by rwightman** [kakaobrain/coyo-dataset#11]
Hello, thanks for releasing the dataset.

A questiong about the data filtering. Did you happen to use either B/32, L/14 (or both) similarity scores in your image-text filtering from Common Crawl? If yes, can you share the threshold(s) used? 

 It's not mentioned in your list of filtering but you do have both B/32 and L/14 CLIP similarity scores in your metadata.

Thanks

**Comment by justHungryMan** [comment]
Hi @rwightman,
We did not filter using similarity score.
We give users the option to customize their filtering strategy by providing similarity scores.

Thanks.

**Comment by rwightman** [comment]
@justHungryMan thanks for the info!
