### ISSUE TITLE
Dimension of phash

### ISSUE THREAD

**Issue by yzou2** [kakaobrain/coyo-dataset#14]
Hi, thanks for providing the great dataset. Just curious, what's the dimension of your phash? Is it the standard 64 dimension?

**Comment by mwbyeon** [comment]
@yzou2 Hi.

You're right, we use the 64-bit standard pHash and represent it as a hexadecimal string. (e.g. "bac58374982e0fc7")
However, 64-bit hashes like pHash are not sufficient to handle billions of web-scale data, so we plan to change to 128-bit or 256-bit hashes in the future.

**Comment by yzou2** [comment]
Thanks a lot for your prompt response!
