### ISSUE TITLE
Average caption length for COYO-700M

### ISSUE THREAD

**Issue by BIGBALLON** [kakaobrain/coyo-dataset#15]
is there any dataset analyse for COYO-700M, especially the average caption length?

**Comment by mwbyeon** [comment]
See the links below.
https://github.com/kakaobrain/coyo-dataset?tab=readme-ov-file#statistics
https://lookerstudio.google.com/reporting/d0929bbe-e617-4a2d-8e84-ec349a97e3d0/page/p_654gl4u4xc?s=jvwkG5XCzYI

**Comment by BIGBALLON** [comment]
@mwbyeon thanks !!!
