### ISSUE TITLE
Spark job failing

### ISSUE THREAD

**Issue by zrtvwp** [kakaobrain/coyo-dataset#3]
Hi. I'm having trouble starting the job, any idea what the problem is?

[google-cloud-dataproc-metainfo.txt](https://github.com/kakaobrain/coyo-dataset/files/9598867/google-cloud-dataproc-metainfo.txt)

**Comment by mwbyeon** [comment]
@zrtvwp Hi.

`Exception: No file found at path mlops-dataset-coyo/dataset/coyo-700m/parquet/ with extension parquet`

Is it correct that parquet files are stored in the path specified in `--url_list`?
please, check if parquet files exist in the specified path.
(e.g `gsutil ls gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/`)

**Comment by zrtvwp** [comment]
> gsutil ls gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/

<img width="1300" alt="Screenshot 2022-09-19 at 16 37 51" src="https://user-images.githubusercontent.com/31877193/191030375-4a48fd2f-e1bf-4164-a4f8-bf3fc5e75464.png">

I removed the slash after parquet folder and got different one: 

[google-cloud-dataproc-metainfo_fc9df8c9.txt](https://github.com/kakaobrain/coyo-dataset/files/9599461/google-cloud-dataproc-metainfo_fc9df8c9.txt)

job look like this: 

```
gcloud dataproc jobs submit pyspark --cluster=coyo-700m --region=us-central1 dataproc-img2dataset.py -- \
    --url_list=gs://mlops-dataset-coyo/dataset/coyo-700m/parquet \
    --input_format="parquet" \
    --url_col="url" \
    --caption_col="text" \
    --output_format=webdataset \
    --output_folder=gs://mlops-dataset-coyo/dataset/coyo-700m/webdataset \
    --distributor="pyspark" \
    --processes_count=1 \
    --thread_count=64 \
    --image_size=384 \
    --retries=1 \
    --min_image_size=200 \
    --max_aspect_ratio=3 \
    --resize_only_if_bigger=True \
    --resize_mode="keep_ratio" \
    --skip_reencode=True \
    --save_additional_columns='["clip_similarity_vitb32","clip_similarity_vitl14","nsfw_score_opennsfw2","nsfw_score_gantman","watermark_score","aesthetic_score_laion_v2"]' \
    --enable_wandb=False
```

**Comment by mwbyeon** [comment]
@zrtvwp Thank you for your information.

I have the same experience. This can happen if old gcsfs installed.
Did you specify `--initialization-actions` argument when creating the DataProc cluster?
(see https://github.com/kakaobrain/coyo-dataset/tree/main/download#download-using-google-cloud-dataproc)
This script installs `img2dataset` and then upgrades `gcsfs`.

**Comment by zrtvwp** [comment]
> @zrtvwp Thank you for your information.
> 
> I have the same experience. This can happen if old gcsfs installed. Did you specify `--initialization-actions` argument when creating the DataProc cluster? (see https://github.com/kakaobrain/coyo-dataset/tree/main/download#download-using-google-cloud-dataproc) This script installs `img2dataset` and then upgrades `gcsfs`.


<img width="626" alt="Screenshot 2022-09-19 at 18 53 16" src="https://user-images.githubusercontent.com/31877193/191061128-dea4b775-b03b-4031-8e3c-679f79f2fde7.png">

Master vm, looks like both commands from script worked well: 

<img width="813" alt="Screenshot 2022-09-19 at 18 58 00" src="https://user-images.githubusercontent.com/31877193/191061131-e2905437-d6e1-4a20-a858-f41230beccb4.png">

**Comment by mwbyeon** [comment]
@zrtvwp 
Could you tell me the version of `img2dataset`, `gcsfs`, `fsspec`?
Check if you can access the path(`gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/`) on the master node.

I will test it tomorrow.

**Comment by zrtvwp** [comment]
> gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/

Thank you for your help

<img width="1295" alt="Screenshot 2022-09-20 at 14 59 53" src="https://user-images.githubusercontent.com/31877193/191252123-5b162d4a-8eb6-4bef-baaf-e3199b3f60f1.png">

**Comment by zrtvwp** [comment]
any updates? 😺

**Comment by mwbyeon** [comment]
@zrtvwp sorry for the late reply.
I also reproduced the same problem.

1. `url_list` must not be followed by `/`, because `/*` is appended to the end of `url_list` in `img2dataset/reader.py` (I'll edit the README.md)

2. Because `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` **FILE(not directory)** exists,
it is not recognized as a directory.
Please delete the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file and try again.

See the code below for details.
https://github.com/rom1504/img2dataset/blob/c6df1996e576e3db8bc16b84e4bd9b644cc35de9/img2dataset/reader.py#L49-L54

**Comment by zrtvwp** [comment]
> @zrtvwp sorry for the late reply. I also reproduced the same problem.
> 
> 1. `url_list` must not be followed by `/`, because `/*` is appended to the end of `url_list` in `img2dataset/reader.py` (I'll edit the README.md)
> 2. Because `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` **FILE(not directory)** exists,
>    it is not recognized as a directory.
>    Please delete the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file and try again.
> 
> See the code below for details. https://github.com/rom1504/img2dataset/blob/c6df1996e576e3db8bc16b84e4bd9b644cc35de9/img2dataset/reader.py#L49-L54

1. But I wrote above that I tried without / and got different kind of output. 
2. So this folder contains parquet files, what file i have to delete? All of them? One? Why was I downloading these parquets then? Im missing some core information.

**Comment by mwbyeon** [comment]
@zrtvwp 

> https://cloud.google.com/storage/docs/folders
Cloud Storage operates with a flat namespace, which means that folders don't actually exist within Cloud Storage. If you create an object named folder1/file.txt in the bucket your-bucket, the path to the object is your-bucket/folder1/file.txt, but there is no folder named folder1; instead, the string folder1 is part of the object's name.

Because the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file exists, the sub-files are not found. 
Since it's not a real directory, deleting this file doesn't delete any sub-files.

**Comment by zrtvwp** [comment]
> @zrtvwp
> 
> > https://cloud.google.com/storage/docs/folders
> > Cloud Storage operates with a flat namespace, which means that folders don't actually exist within Cloud Storage. If you create an object named folder1/file.txt in the bucket your-bucket, the path to the object is your-bucket/folder1/file.txt, but there is no folder named folder1; instead, the string folder1 is part of the object's name.
> 
> Because the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file exists, the sub-files are not found. Since it's not a real directory, deleting this file doesn't delete any sub-files.

Is there any way around this feature? Could gs://bucket/*.parquet straight path works?

**Comment by mwbyeon** [comment]
@zrtvwp 
Just delete the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file (not *.parquet files) and submit a job with dataproc again.
`$ gsutil rm gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/`

**Comment by zrtvwp** [comment]
> ch means that folders don't actually exist within Cloud Storage. If you create an object named folder1/file.txt in the bucket your-bucket, the path to the object is your-bucket/folder1/file.txt, but there is no folder named folder1;

Thank you, it worked. I understood the part about folders being part of object names. but I did not understand what we delete here: gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/  and how this part of object name is interpreted as a file.

Are we removing / after parquet in that command so url_list can read the files?

**Comment by mwbyeon** [comment]
@zrtvwp 

In GCS, even if it ends with "/", it's just an object's name.

See [img2dataset/reader.py#L49-L54](https://github.com/rom1504/img2dataset/blob/c6df1996e576e3db8bc16b84e4bd9b644cc35de9/img2dataset/reader.py#L49-L54)
If the `gs://mlops-dataset-coyo/dataset/coyo-700m/parquet/` file exists, only this file is read because it is not a directory.
If this path does not exist, it is searched by appending `*.parquet` after the path.

**Comment by zrtvwp** [comment]
Thank you. I really appreciate your help.

**Comment by mwbyeon** [comment]
@zrtvwp you're welcome.
If you have any other questions, feel free to create a new issue.
